### ISSUE TITLE
Instance deserialized although modelType is missing

### ISSUE THREAD

**Issue by bjoern-otto** [aas-core-works/aas-core3.0-python#32]
Shouldn't the following instance be rejected? The `modelType` is missing.

```json
{
    "assetAdministrationShells": [
        {
            "extensions": [
                {
                    "name": "x"
                }
            ],
            "id": "x",
            "assetInformation": {
                "assetKind": "Instance",
                "globalAssetId": "x"
            }
        }
    ]
}
```

**Comment by mristin** [comment]
Thanks, @otto-ifak ! Indeed, it should! Since we always know the type, there is no discrimination, so the de-serialization never fired on missing model type as it never used it.

I also see that I did not include the missing `modelType` cases in aas-core-testgen JSON test as I only iterated over the meta-model properties, but not the additional properties not explicitly specified in the meta-model such as `modelType`.

Both these issues need to be fixed.

**Comment by mristin** [comment]
Thanks again, @otto-ifak ! Are there any more pending issues or errors you'd like to report, or should I release a new patch version of the SDK?

**Comment by bjoern-otto** [comment]
@mristin You are welcome. Maybe I found one more:
https://github.com/aas-core-works/aas-core3.0-python/issues/37

If you could wait till the end of the week for the next release, I should be done checking for errors.

**Comment by mristin** [comment]
@otto-ifak sure, let's wait, no problem at all!
