### ISSUE TITLE
FRAGMENT_KEYS enum is missing Referable

### ISSUE THREAD

**Issue by bjoern-otto** [aas-core-works/aas-core3.0-python#37]
According to the spec, `Referable` is part of of `FragmentKeys`, but it is missing in the code:

https://github.com/aas-core-works/aas-core3.0-python/blob/3d2965498d0e271ae4b0a0af13e06316620cb2f4/aas_core3/constants.py#L107

As a result, Constraint AASd-125 is not implemented correctly.

![image](https://github.com/user-attachments/assets/9ea6765a-45cd-4ed1-98c5-bbd1c4a644b3)

**Comment by mristin** [comment]
@zgrt @s-heppner could you please check? This seems like an issue with aas-core-meta/v3.py?

Here would be the related line in aas-core-meta:
https://github.com/aas-core-works/aas-core-meta/blob/6d5411bf9f5ef0ccc1ed956c63c2eca50711137f/aas_core_meta/v3.py#L4919

**Comment by s-heppner** [comment]
I think that has to do with the fact that `Referable` is an abstract class an can therefore not be used as `FragmentKey` directly.

**Comment by mristin** [comment]
@s-heppner this issue is not related to classes. I think we either forgot to add the enumeration literal to the respective constant set *or* the specs silently changed inbetween.

I'll try to have a closer look tomorrow.

**Comment by mristin** [comment]
@s-heppner sorry for the delay; I have to first fix `modelType` checks in all the SDKs (+Java SDK needs to be fixed by @empwilli). I'll try to come back to this issue as soon as possible, hopefully before end of July.

**Comment by mristin** [comment]
I had another pass over this. This seems to be a bug in the specs!

@s-heppner is correct. `Referable` is an abstract class, so *identifiable* classes such as `Asset Administration Shell` and `Submodel` inherit from it. The constant sets over `KeyTypes` reflect this hierarchy. Thus, the constant set `AasReferableNonIdentifiables` *should not* include the literal `Referable`.

@s-heppner can you please have another look at this, and propagate this back to IDTA and see what the desired course of action would be?

Maybe we should simply write out the fragment keys as a separate constant set which does not "inherit" from `AasReferableNonIdentifiables`?

**Comment by mristin** [comment]
I decided to fix aas-core-meta to follow the specs literally, even though the specs is self-contradictory:
https://github.com/aas-core-works/aas-core-meta/pull/337

Here's the relevant excerpt from the patch description:

> It is important to note here that the specification ("the book") is broken. Namely, the constant set `AAS_referables_non_identifiables` *can not* contain `Referable` literal as all identifiables are also referables. Hence, referables + non-identifiables *can not* also contain general referables which would be identifiables, leading to a contradiction.
>
> We finally decided to follow the book even though the constant set `AAS_referables_non_identifiables` is either broken or a misnomer.

I will propagate this change (along with all the other changes for v3.0.2) to the SDKs mid-August 2024.

**Comment by s-heppner** [comment]
I have just learned that these UML-Diagrams are **not normative**.
Sadly, this is not mentioned directly, however it is implied with:

> Figure 49 presents a logical model of key types. These logical enumerations are used to formulate constraints.

The inheritance of enumerators is only meant to help the reader understand where the enumerator values come from, no one is expected to implement inheritance of enumerators (as most programming languages do not allow to inherit an immutable set of constants anyway). 

What **is normative** are the tables below the figure.

In this table, `Referable` is not part of `AAS_referables_non_identifiables`. 
Therefore we were not wrong in the first place with our implementation. 

@mristin sadly that means, we need to revert your changes yet again.

By the way, the figure is fixed in the bugfix release [v3.0.1 of the specification](https://industrialdigitaltwin.org/wp-content/uploads/2024/06/IDTA-01001-3-0-1_SpecificationAssetAdministrationShell_Part1_Metamodel.pdf#Page=83)

I will open a discussion in the specification team to prohibit abstract classes in enumerators, in order to avoid similar paradoxes in the future.

**Comment by mristin** [comment]
@s-heppner can you please take over the revert?

**Comment by mristin** [comment]
I'm closing this issue as it turned out to be a bug in specification.
