### ISSUE TITLE
Constraint AASc-002 has been renamed to AASc-3a-002

### ISSUE THREAD

**Issue by bjoern-otto** [aas-core-works/aas-core3.0-python#38]
Should be renamed to be in sync with the spec.

**Comment by mristin** [comment]
Happening today 😀

**Comment by mristin** [comment]
Due to the issue https://github.com/aas-core-works/aas-core3.0-csharp/issues/38, which affects aas-core-meta, I will wait with the new release of the SDKs. I will propagate the changes from aas-core-meta, though.

Does that work for you, @otto-ifak ? I suppose you can check out the Python SDK from main for testing, right?

**Comment by mristin** [comment]
The change is in the main branch now. @otto-ifak can you please check, and if everything works, close this issue?

**Comment by bjoern-otto** [comment]
@mristin yes, I will check using the python Sdk tomorrow

**Comment by mristin** [comment]
I updated all the SDKs to V3.0.1 including this change as well. I'll close the issue for now -- please re-open if it persists.
